#include<stdio.h>
#include<unistd.h>
int main(int argc, char **argv){

    if(strcmp(argv[1], "cd")==0){
        printf("NAME\n"
               "    cd - Change the shell working directory.\n"
               "\n"
               "SYNOPSIS\n"
               "    cd [-L|[-P [-e]] [-@]] [dir]\n"
               "\n"
               "DESCRIPTION\n"
               "    Change the shell working directory.\n"
               "    \n"
               "    Change the current directory to DIR.  The default DIR is the value of the\n"
               "    HOME shell variable.\n"
               "    \n"
               "    The variable CDPATH defines the search path for the directory containing\n"
               "    DIR.  Alternative directory names in CDPATH are separated by a colon (:).\n"
               "    A null directory name is the same as the current directory.  If DIR begins\n"
               "    with a slash (/), then CDPATH is not used.\n"
               "    \n"
               "    If the directory is not found, and the shell option `cdable_vars' is set,\n"
               "    the word is assumed to be  a variable name.  If that variable has a value,\n"
               "    its value is used for DIR.\n"
               "    \n"
               "    Options:\n"
               "      -L\tforce symbolic links to be followed: resolve symbolic\n"
               "    \t\tlinks in DIR after processing instances of `..'\n"
               "      -P\tuse the physical directory structure without following\n"
               "    \t\tsymbolic links: resolve symbolic links in DIR before\n"
               "    \t\tprocessing instances of `..'\n"
               "      -e\tif the -P option is supplied, and the current working\n"
               "    \t\tdirectory cannot be determined successfully, exit with\n"
               "    \t\ta non-zero status\n"
               "      -@\ton systems that support it, present a file with extended\n"
               "    \t\tattributes as a directory containing the file attributes\n"
               "    \n"
               "    The default is to follow symbolic links, as if `-L' were specified.\n"
               "    `..' is processed by removing the immediately previous pathname component\n"
               "    back to a slash or the beginning of DIR.\n"
               "    \n"
               "    Exit Status:\n"
               "    Returns 0 if the directory is changed, and if $PWD is set successfully when\n"
               "    -P is used; non-zero otherwise.\n"
               "\n"
               "SEE ALSO\n"
               "    bash(1)\n"
               "\n"
               "IMPLEMENTATION\n"
               "    GNU bash, version 5.0.17(1)-release (x86_64-redhat-linux-gnu)\n"
               "    Copyright (C) 2019 Free Software Foundation, Inc.\n"
               "    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\n");

    }else if(strcmp(argv[1], "ls")==0){
                printf("LS(1)                         User Commands                         LS(1)\n"
                       "\n"
                       "NAME\n"
                       "       ls - list directory contents\n"
                       "\n"
                       "SYNOPSIS\n"
                       "       ls [OPTION]... [FILE]...\n"
                       "\n"
                       "DESCRIPTION\n"
                       "       List  information  about  the  FILEs  (the  current  directory  by\n"
                       "       default).  Sort entries alphabetically if none  of  -cftuvSUX  nor\n"
                       "       --sort is specified.\n"
                       "\n"
                       "       Mandatory  arguments  to  long  options  are  mandatory  for short\n"
                       "       options too.\n"
                       "\n"
                       "       -l     use a long listing format\n"
                       "\n"
                       "       The SIZE argument is an integer and optional unit (example: 10K is\n"
                       "       10*1024).  Units are K,M,G,T,P,E,Z,Y (powers of 1024) or KB,MB,...\n"
                       "       (powers of 1000).  Binary prefixes can be used, too: KiB=K, MiB=M,\n"
                       "       and so on.\n"
                       "\n"
                       "       The TIME_STYLE argument can be full-iso, long-iso, iso, locale, or\n"
                       "       +FORMAT.  FORMAT is interpreted like in  date(1).   If  FORMAT  is\n"
                       "       FORMAT1<newline>FORMAT2,  then FORMAT1 applies to non-recent files\n"
                       "       and FORMAT2 to recent files.  TIME_STYLE  prefixed  with  'posix-'\n"
                       "       takes  effect  only outside the POSIX locale.  Also the TIME_STYLE\n"
                       "       environment variable sets the default style to use.\n"
                       "\n"
                       "       Using color to distinguish file types is disabled both by  default\n"
                       "       and  with  --color=never.  With --color=auto, ls emits color codes\n"
                       "       only when standard output is connected to a terminal.  The LS_COL‐\n"
                       "       ORS environment variable can change the settings.  Use the dircol‐\n"
                       "       ors command to set it.\n"
                       "\n"
                       "   Exit status:\n"
                       "       0      if OK,\n"
                       "\n"
                       "       1      if minor problems (e.g., cannot access subdirectory),\n"
                       "\n"
                       "       2      if serious trouble (e.g., cannot access command-line  argu‐\n"
                       "              ment).\n"
                       "\n"
                       "AUTHOR\n"
                       "       Written by Richard M. Stallman and David MacKenzie.\n"
                       "\n"
                       "REPORTING BUGS\n"
                       "       GNU  coreutils  online  help:  <https://www.gnu.org/software/core‐\n"
                       "       utils/>\n"
                       "       Report   any   translation   bugs   to    <https://translationpro‐\n"
                       "       ject.org/team/>\n"
                       "\n"
                       "COPYRIGHT\n"
                       "       Copyright  ©  2020 Free Software Foundation, Inc.  License GPLv3+:\n"
                       "       GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n"
                       "       This is free software: you are free to change and redistribute it.\n"
                       "       There is NO WARRANTY, to the extent permitted by law.\n"
                       "\n"
                       "SEE ALSO\n"
                       "       Full documentation <https://www.gnu.org/software/coreutils/ls>\n"
                       "       or available locally via: info '(coreutils) ls invocation'\n"
                       "\n"
                       "GNU coreutils 8.32              April 2020                          LS(1)\n");
    }else if(strcmp(argv[1], "pwd")==0){
        printf("NAME\n"
               "    pwd - Print the name of the current working directory.\n"
               "\n"
               "SYNOPSIS\n"
               "    pwd [-LP]\n"
               "\n"
               "DESCRIPTION\n"
               "    Print the name of the current working directory.\n"
               "    \n"
               "    Options:\n"
               "      -L\tprint the value of $PWD if it names the current working\n"
               "    \t\tdirectory\n"
               "      -P\tprint the physical directory, without any symbolic links\n"
               "    \n"
               "    By default, `pwd' behaves as if `-L' were specified.\n"
               "    \n"
               "    Exit Status:\n"
               "    Returns 0 unless an invalid option is given or the current directory\n"
               "    cannot be read.\n"
               "\n"
               "SEE ALSO\n"
               "    bash(1)\n"
               "\n"
               "IMPLEMENTATION\n"
               "    GNU bash, version 5.0.17(1)-release (x86_64-redhat-linux-gnu)\n"
               "    Copyright (C) 2019 Free Software Foundation, Inc.\n"
               "    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\n");
    }else if(strcmp(argv[1], "cat")==0){
        printf("CAT(1)                        User Commands                        CAT(1)\n"
               "\n"
               "NAME\n"
               "       cat - concatenate files and print on the standard output\n"
               "\n"
               "SYNOPSIS\n"
               "       cat [OPTION]... [FILE]...\n"
               "\n"
               "DESCRIPTION\n"
               "       Concatenate FILE(s) to standard output.\n"
               "\n"
               "       With no FILE, or when FILE is -, read standard input.\n"
               "\n!"
               "       cat    Copy standard input to standard output.\n"
               "\n"
               "AUTHOR\n"
               "       Written by Torbjorn Granlund and Richard M. Stallman.\n"
               "\n"
               "REPORTING BUGS\n"
               "       GNU  coreutils  online  help:  <https://www.gnu.org/software/core‐\n"
               "       utils/>\n"
               "       Report    any   translation   bugs   to   <https://translationpro‐\n"
               "       ject.org/team/>\n"
               "\n"
               "COPYRIGHT\n"
               "       Copyright © 2020 Free Software Foundation, Inc.   License  GPLv3+:\n"
               "       GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n"
               "       This is free software: you are free to change and redistribute it.\n"
               "       There is NO WARRANTY, to the extent permitted by law.\n"
               "\n"
               "SEE ALSO\n"
               "       tac(1)\n"
               "\n"
               "       Full documentation <https://www.gnu.org/software/coreutils/cat>\n"
               "       or available locally via: info '(coreutils) cat invocation'\n"
               "\n"
               "GNU coreutils 8.32              April 2020                         CAT(1)\n");

    }else if(strcmp(argv[1], "touch")==0){
        printf("TOUCH(1)                      User Commands                      TOUCH(1)\n"
               "\n"
               "NAME\n"
               "       touch - change file timestamps\n"
               "\n"
               "SYNOPSIS\n"
               "       touch [OPTION]... FILE...\n"
               "\n"
               "DESCRIPTION\n"
               "       Update  the access and modification times of each FILE to the cur‐\n"
               "       rent time.\n"
               "\n"
               "       A FILE argument that does not exist is created empty, unless -c or\n"
               "       -h is supplied.\n"
               "\n"
               "       A  FILE argument string of - is handled specially and causes touch\n"
               "       to change the times of the file associated with standard output.\n"
               "\n"
               "       Mandatory arguments  to  long  options  are  mandatory  for  short\n"
               "       options too.\n"
               "\n"
               "       Note that the -d and -t options accept  different  time-date  for‐\n"
               "       mats.\n"
               "\n"
               "DATE STRING\n"
               "       The  --date=STRING  is  a  mostly  free format human readable date\n"
               "       string such as \"Sun, 29 Feb 2004 16:21:42  -0800\"  or  \"2004-02-29\n"
               "       16:21:42\"  or  even  \"next  Thursday\".   A date string may contain\n"
               "       items indicating calendar date, time of day,  time  zone,  day  of\n"
               "       week,  relative time, relative date, and numbers.  An empty string\n"
               "       indicates the beginning of the day.  The  date  string  format  is\n"
               "       more complex than is easily documented here but is fully described\n"
               "       in the info documentation.\n"
               "\n"
               "AUTHOR\n"
               "       Written by Paul Rubin, Arnold Robbins, Jim Kingdon, David  MacKen‐\n"
               "       zie, and Randy Smith.\n"
               "\n"
               "REPORTING BUGS\n"
               "       GNU  coreutils  online  help:  <https://www.gnu.org/software/core‐\n"
               "       utils/>\n"
               "       Report   any   translation   bugs   to    <https://translationpro‐\n"
               "       ject.org/team/>\n"
               "\n"
               "COPYRIGHT\n"
               "       Copyright  ©  2020 Free Software Foundation, Inc.  License GPLv3+:\n"
               "       GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n"
               "       This is free software: you are free to change and redistribute it.\n"
               "       There is NO WARRANTY, to the extent permitted by law.\n"
               "\n"
               "SEE ALSO\n"
               "       Full documentation <https://www.gnu.org/software/coreutils/touch>\n"
               "       or available locally via: info '(coreutils) touch invocation'\n"
               "\n"
               "GNU coreutils 8.32              April 2020                       TOUCH(1)\n");

    }else if(strcmp(argv[1], "mv")==0){
    printf("MV(1)                         User Commands                         MV(1)\n"
           "\n"
           "NAME\n"
           "       mv - move (rename) files\n"
           "\n"
           "SYNOPSIS\n"
           "       mv [OPTION]... [-T] SOURCE DEST\n"
           "       mv [OPTION]... SOURCE... DIRECTORY\n"
           "       mv [OPTION]... -t DIRECTORY SOURCE...\n"
           "\n"
           "DESCRIPTION\n"
           "       Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY.\n"
           "\n"
           "       Mandatory  arguments  to  long  options  are  mandatory  for short\n"
           "       options too.\n"
           "\n"
           "AUTHOR\n"
           "       Written by Mike Parker, David MacKenzie, and Jim Meyering.\n"
           "\n"
           "REPORTING BUGS\n"
           "       GNU  coreutils  online  help:  <https://www.gnu.org/software/core‐\n"
           "       utils/>\n"
           "       Report    any   translation   bugs   to   <https://translationpro‐\n"
           "       ject.org/team/>\n"
           "\n"
           "COPYRIGHT\n"
           "       Copyright © 2020 Free Software Foundation, Inc.   License  GPLv3+:\n"
           "       GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n"
           "       This is free software: you are free to change and redistribute it.\n"
           "       There is NO WARRANTY, to the extent permitted by law.\n"
           "\n"
           "SEE ALSO\n"
           "       rename(2)\n"
           "\n"
           "       Full documentation <https://www.gnu.org/software/coreutils/mv>\n"
           "       or available locally via: info '(coreutils) mv invocation'\n"
           "\n"
           "GNU coreutils 8.32              April 2020                          MV(1)\n");

    }else if(strcmp(argv[1], "cp")==0){

        printf("CP(1)                         User Commands                         CP(1)\n"
               "\n"
               "NAME\n"
               "       cp - copy files and directories\n"
               "\n"
               "SYNOPSIS\n"
               "       cp [OPTION]... [-T] SOURCE DEST\n"
               "       cp [OPTION]... SOURCE... DIRECTORY\n"
               "       cp [OPTION]... -t DIRECTORY SOURCE...\n"
               "\n"
               "DESCRIPTION\n"
               "       Copy SOURCE to DEST, or multiple SOURCE(s) to DIRECTORY.\n"
               "\n"
               "       Mandatory  arguments  to  long  options  are  mandatory  for short\n"
               "       options too.\n"
               "\n"
               "       By  default, sparse SOURCE files are detected by a crude heuristic\n"
               "       and the corresponding DEST file is made sparse as well.   That  is\n"
               "       the  behavior  selected by --sparse=auto.  Specify --sparse=always\n"
               "       to create a sparse DEST file whenever the SOURCE file  contains  a\n"
               "       long enough sequence of zero bytes.  Use --sparse=never to inhibit\n"
               "       creation of sparse files.\n"
               "\n"
               "       When --reflink[=always] is specified, perform a lightweight  copy,\n"
               "       where  the  data blocks are copied only when modified.  If this is\n"
               "       not possible the copy fails, or if  --reflink=auto  is  specified,\n"
               "       fall  back  to  a  standard copy.  Use --reflink=never to ensure a\n"
               "       standard copy is performed.\n"
               "\n"
               "       The backup suffix  is  '~',  unless  set  with  --suffix  or  SIM‐\n"
               "       PLE_BACKUP_SUFFIX.  The version control method may be selected via\n"
               "       the --backup option or  through  the  VERSION_CONTROL  environment\n"
               "       variable.  Here are the values:\n"
               "\n"
               "       none, off\n"
               "              never make backups (even if --backup is given)\n"
               "\n"
               "       numbered, t\n"
               "              make numbered backups\n"
               "\n"
               "       existing, nil\n"
               "              numbered if numbered backups exist, simple otherwise\n"
               "\n"
               "       simple, never\n"
               "              always make simple backups\n"
               "\n"
               "       As  a special case, cp makes a backup of SOURCE when the force and\n"
               "       backup options are given and SOURCE and DEST are the same name for\n"
               "       an existing, regular file.\n"
               "\n"
               "AUTHOR\n"
               "       Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.\n"
               "\n"
               "REPORTING BUGS\n"
               "       GNU  coreutils  online  help:  <https://www.gnu.org/software/core‐\n"
               "       utils/>\n"
               "       Report   any   translation   bugs   to    <https://translationpro‐\n"
               "       ject.org/team/>\n"
               "\n"
               "COPYRIGHT\n"
               "       Copyright  ©  2020 Free Software Foundation, Inc.  License GPLv3+:\n"
               "       GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n"
               "       This is free software: you are free to change and redistribute it.\n"
               "       There is NO WARRANTY, to the extent permitted by law.\n"
               "\n"
               "SEE ALSO\n"
               "       Full documentation <https://www.gnu.org/software/coreutils/cp>\n"
               "       or available locally via: info '(coreutils) cp invocation'\n"
               "\n"
               "GNU coreutils 8.32              April 2020                          CP(1)\n");

    }else if(strcmp(argv[1], "grep")==0){

        printf("GREP(1)                       User Commands                       GREP(1)\n"
               "\n"
               "NAME\n"
               "       grep, egrep, fgrep - print lines that match patterns\n"
               "\n"
               "SYNOPSIS\n"
               "       grep [OPTION...] PATTERNS [FILE...]\n"
               "       grep [OPTION...] -e PATTERNS ... [FILE...]\n"
               "       grep [OPTION...] -f PATTERN_FILE ... [FILE...]\n"
               "\n"
               "DESCRIPTION\n"
               "       grep  searches  for  PATTERNS  in  each  FILE.  PATTERNS is one or\n"
               "       patterns separated by newline characters,  and  grep  prints  each\n"
               "       line that matches a pattern.\n"
               "\n"
               "       A  FILE  of  “-”  stands for standard input.  If no FILE is given,\n"
               "       recursive searches examine the working directory, and nonrecursive\n"
               "       searches read standard input.\n"
               "\n"
               "       In  addition, the variant programs egrep and fgrep are the same as\n"
               "       grep -E and grep -F, respectively.  These variants are deprecated,\n"
               "       but are provided for backward compatibility.\n"
               "\n"
               "REGULAR EXPRESSIONS\n"
               "       A regular expression is a pattern that describes a set of strings.\n"
               "       Regular  expressions  are  constructed  analogously  to arithmetic\n"
               "       expressions,  by  using  various  operators  to  combine   smaller\n"
               "       expressions.\n"
               "\n"
               "       grep  understands  three  different versions of regular expression\n"
               "       syntax: “basic” (BRE), “extended” (ERE) and “perl” (PCRE).  In GNU\n"
               "       grep  there  is  no  difference in available functionality between\n"
               "       basic and extended  syntaxes.   In  other  implementations,  basic\n"
               "       regular  expressions are less powerful.  The following description\n"
               "       applies to extended regular  expressions;  differences  for  basic\n"
               "       regular  expressions  are  summarized afterwards.  Perl-compatible\n"
               "       regular  expressions  give  additional  functionality,   and   are\n"
               "       documented  in  pcresyntax(3) and pcrepattern(3), but work only if\n"
               "       PCRE is available in the system.\n"
               "\n"
               "       The fundamental building blocks are the regular  expressions  that\n"
               "       match  a single character.  Most characters, including all letters\n"
               "       and digits, are regular expressions that  match  themselves.   Any\n"
               "       meta-character  with special meaning may be quoted by preceding it\n"
               "       with a backslash.\n"
               "\n"
               "       The period . matches any  single  character.   It  is  unspecified\n"
               "       whether it matches an encoding error.\n"
               "\n"
               "   Character Classes and Bracket Expressions\n"
               "       A  bracket expression is a list of characters enclosed by [ and ].\n"
               "       It matches any single  character  in  that  list.   If  the  first\n"
               "       character of the list is the caret ^ then it matches any character\n"
               "       not in the list; it is unspecified whether it matches an  encoding\n"
               "       error.   For  example, the regular expression [0123456789] matches\n"
               "       any single digit.\n"
               "\n"
               "       Within a bracket expression, a range expression  consists  of  two\n"
               "       characters separated by a hyphen.  It matches any single character\n"
               "       that sorts  between  the  two  characters,  inclusive,  using  the\n"
               "       locale's  collating  sequence  and character set.  For example, in\n"
               "       the default C locale, [a-d] is equivalent to [abcd].  Many locales\n"
               "       sort characters in dictionary order, and in these locales [a-d] is\n"
               "       typically not equivalent to [abcd];  it  might  be  equivalent  to\n"
               "       [aBbCcDd],  for example.  To obtain the traditional interpretation\n"
               "       of bracket expressions, you can use the C locale  by  setting  the\n"
               "       LC_ALL environment variable to the value C.\n"
               "\n"
               "       Finally, certain named classes of characters are predefined within\n"
               "       bracket  expressions,  as   follows.    Their   names   are   self\n"
               "       explanatory,   and   they  are  [:alnum:],  [:alpha:],  [:cntrl:],\n"
               "       [:digit:], [:graph:], [:lower:], [:print:], [:punct:],  [:space:],\n"
               "       [:upper:],  and  [:xdigit:].   For  example, [[:alnum:]] means the\n"
               "       character class of numbers and letters in the current locale.   In\n"
               "       the C locale and ASCII character set encoding, this is the same as\n"
               "       [0-9A-Za-z].  (Note that the brackets in  these  class  names  are\n"
               "       part  of  the  symbolic names, and must be included in addition to\n"
               "       the brackets  delimiting  the  bracket  expression.)   Most  meta-\n"
               "       characters  lose their special meaning inside bracket expressions.\n"
               "       To include a literal ] place it first in the list.  Similarly,  to\n"
               "       include  a  literal  ^  place  it anywhere but first.  Finally, to\n"
               "       include a literal - place it last.\n"
               "\n"
               "   Anchoring\n"
               "       The caret ^  and  the  dollar  sign  $  are  meta-characters  that\n"
               "       respectively  match the empty string at the beginning and end of a\n"
               "       line.\n"
               "\n"
               "   The Backslash Character and Special Expressions\n"
               "       The symbols \\< and \\> respectively match the empty string  at  the\n"
               "       beginning  and  end  of  a  word.  The symbol \\b matches the empty\n"
               "       string at the edge of a word, and  \\B  matches  the  empty  string\n"
               "       provided  it's  not  at  the  edge  of a word.  The symbol \\w is a\n"
               "       synonym for [_[:alnum:]] and \\W is a synonym for [^_[:alnum:]].\n"
               "\n"
               "   Repetition\n"
               "       A regular expression may be followed by one of several  repetition\n"
               "       operators:\n"
               "       ?      The preceding item is optional and matched at most once.\n"
               "       *      The preceding item will be matched zero or more times.\n"
               "       +      The preceding item will be matched one or more times.\n"
               "       {n}    The preceding item is matched exactly n times.\n"
               "       {n,}   The preceding item is matched n or more times.\n"
               "       {,m}   The  preceding  item is matched at most m times.  This is a\n"
               "              GNU extension.\n"
               "       {n,m}  The preceding item is matched at least  n  times,  but  not\n"
               "              more than m times.\n"
               "\n"
               "   Concatenation\n"
               "       Two regular expressions may be concatenated; the resulting regular\n"
               "       expression  matches  any  string  formed  by   concatenating   two\n"
               "       substrings that respectively match the concatenated expressions.\n"
               "\n"
               "   Alternation\n"
               "       Two regular expressions may be joined by the infix operator |; the\n"
               "       resulting regular expression matches any  string  matching  either\n"
               "       alternate expression.\n"
               "\n"
               "   Precedence\n"
               "       Repetition  takes  precedence  over  concatenation,  which in turn\n"
               "       takes precedence over alternation.   A  whole  expression  may  be\n"
               "       enclosed  in  parentheses  to  override these precedence rules and\n"
               "       form a subexpression.\n"
               "\n"
               "   Back References and Subexpressions\n"
               "       The back-reference \\n, where n is  a  single  digit,  matches  the\n"
               "       substring    previously   matched   by   the   nth   parenthesized\n"
               "       subexpression of the regular expression.\n"
               "\n"
               "   Basic vs Extended Regular Expressions\n"
               "       In basic regular expressions the meta-characters ?, +,  {,  |,  (,\n"
               "       and  )  lose  their  special  meaning; instead use the backslashed\n"
               "       versions \\?, \\+, \\{, \\|, \\(, and \\).\n"
               "\n"
               "EXIT STATUS\n"
               "       Normally the exit status is 0 if a line is selected, 1 if no lines\n"
               "       were selected, and 2 if an error occurred.  However, if the -q  or\n"
               "       --quiet  or  --silent  is  used  and  a line is selected, the exit\n"
               "       status is 0 even if an error occurred.\n"
               "\n"
               "COPYRIGHT\n"
               "       Copyright 1998–2000, 2002,  2005–2018  Free  Software  Foundation,\n"
               "       Inc.\n"
               "\n"
               "       This  is  free  software;  see  the source for copying conditions.\n"
               "       There is NO warranty; not even for MERCHANTABILITY or FITNESS  FOR\n"
               "       A PARTICULAR PURPOSE.\n"
               "\n"
               "BUGS\n"
               "   Reporting Bugs\n"
               "       Email bug reports to the bug-reporting address ⟨bug-grep@gnu.org⟩.\n"
               "       An email archive ⟨https://lists.gnu.org/mailman/listinfo/bug-grep⟩\n"
               "       and                  a                 bug                 tracker\n"
               "       ⟨https://debbugs.gnu.org/cgi/pkgreport.cgi?package=grep⟩       are\n"
               "       available.\n"
               "\n"
               "   Known Bugs\n"
               "       Large  repetition  counts in the {n,m} construct may cause grep to\n"
               "       use lots of memory.  In addition, certain  other  obscure  regular\n"
               "       expressions require exponential time and space, and may cause grep\n"
               "       to run out of memory.\n"
               "\n"
               "       Back-references are very slow, and may require exponential time.\n"
               "\n"
               "SEE ALSO\n"
               "   Regular Manual Pages\n"
               "       awk(1),  cmp(1),  diff(1),  find(1),  gzip(1),  perl(1),   sed(1),\n"
               "       sort(1),  xargs(1),  zgrep(1),  read(2),  pcre(3),  pcresyntax(3),\n"
               "       pcrepattern(3), terminfo(5), glob(7), regex(7).\n"
               "\n"
               "   POSIX Programmer's Manual Page\n"
               "       grep(1p).\n"
               "\n"
               "   Full Documentation\n"
               "       A complete manual  ⟨https://www.gnu.org/software/grep/manual/⟩  is\n"
               "       available.   If  the info and grep programs are properly installed\n"
               "       at your site, the command\n"
               "\n"
               "              info grep\n"
               "\n"
               "       should give you access to the complete manual.\n"
               "\n"
               "NOTES\n"
               "       This man page is maintained only fitfully; the full  documentation\n"
               "       is often more up-to-date.\n"
               "\n"
               "GNU grep 3.3                    2018-05-11                        GREP(1)\n");
    }else if(strcmp(argv[1], "man")==0){

        printf("MAN(1)                      Manual pager utils                     MAN(1)\n"
               "\n"
               "NAME\n"
               "       man - an interface to the system reference manuals\n"
               "\n"
               "SYNOPSIS\n"
               "       man [man options] [[section] page ...] ...\n"
               "\n"
               "DESCRIPTION\n"
               "       man is the system's manual pager.  Each page argument given to man\n"
               "       is normally the name of a program, utility or function.  The  man‐\n"
               "       ual page associated with each of these arguments is then found and\n"
               "       displayed.  A section, if provided, will direct man to  look  only\n"
               "       in that section of the manual.  The default action is to search in\n"
               "       all of the available sections following a pre-defined  order  (see\n"
               "       DEFAULTS),  and  to  show  only the first page found, even if page\n"
               "       exists in several sections.\n"
               "\n"
               "       The table below shows the section numbers of the  manual  followed\n"
               "       by the types of pages they contain.\n"
               "\n"
               "       1   Executable programs or shell commands\n"
               "       2   System calls (functions provided by the kernel)\n"
               "       3   Library calls (functions within program libraries)\n"
               "       4   Special files (usually found in /dev)\n"
               "       5   File formats and conventions, e.g. /etc/passwd\n"
               "       6   Games\n"
               "       7   Miscellaneous (including macro packages and conventions), e.g.\n"
               "           man(7), groff(7)\n"
               "       8   System administration commands (usually only for root)\n"
               "       9   Kernel routines [Non standard]\n"
               "\n"
               "       A manual page consists of several sections.\n"
               "\n"
               "       Conventional section names include NAME, SYNOPSIS,  CONFIGURATION,\n"
               "       DESCRIPTION,  OPTIONS, EXIT STATUS, RETURN VALUE, ERRORS, ENVIRON‐\n"
               "       MENT,  FILES,  VERSIONS,  CONFORMING TO,  NOTES,  BUGS,   EXAMPLE,\n"
               "       AUTHORS, and SEE ALSO.\n"
               "\n"
               "       The following conventions apply to the SYNOPSIS section and can be\n"
               "       used as a guide in other sections.\n"
               "\n"
               "       bold text          type exactly as shown.\n"
               "       italic text        replace with appropriate argument.\n"
               "       [-abc]             any or all arguments within [ ] are optional.\n"
               "       -a|-b              options delimited by | cannot be used together.\n"
               "       argument ...       argument is repeatable.\n"
               "       [expression] ...   entire expression within [ ] is repeatable.\n"
               "\n"
               "       Exact rendering may vary depending  on  the  output  device.   For\n"
               "       instance, man will usually not be able to render italics when run‐\n"
               "       ning in a terminal, and will typically use underlined or  coloured\n"
               "       text instead.\n"
               "\n"
               "       The  command  or  function  illustration  is a pattern that should\n"
               "       match all possible invocations.  In some cases it is advisable  to\n"
               "       illustrate several exclusive invocations as is shown in the SYNOP‐\n"
               "       SIS section of this manual page.\n"
               "\n"
               "EXAMPLES\n"
               "       man ls\n"
               "           Display the manual page for the item (program) ls.\n"
               "\n"
               "OVERVIEW\n"
               "       Many options are available to man in order to give as much  flexi‐\n"
               "       bility as possible to the user.  Changes can be made to the search\n"
               "       path, section order, output processor, and  other  behaviours  and\n"
               "       operations detailed below.\n"
               "\n"
               "       If  set,  various environment variables are interrogated to deter‐\n"
               "       mine the operation of man.  It is possible to set the  \"catch-all\"\n"
               "       variable  $MANOPT  to  any string in command line format, with the\n"
               "       exception that any spaces used as part  of  an  option's  argument\n"
               "       must be escaped (preceded by a backslash).  man will parse $MANOPT\n"
               "       prior to parsing its own command line.  Those options requiring an\n"
               "       argument  will be overridden by the same options found on the com‐\n"
               "       mand line.  To reset all of the options set in $MANOPT, -D can  be\n"
               "       specified as the initial command line option.  This will allow man\n"
               "       to \"forget\" about the options specified in $MANOPT, although  they\n"
               "       must still have been valid.\n"
               "\n"
               "       Manual pages are normally stored in nroff(1) format under a direc‐\n"
               "       tory such as /usr/share/man.  In  some  installations,  there  may\n"
               "       also  be  preformatted cat pages to improve performance.  See man‐\n"
               "       path(5) for details of where these files are stored.\n"
               "\n"
               "       This package supports manual pages  in  multiple  languages,  con‐\n"
               "       trolled  by  your  locale.  If your system did not set this up for\n"
               "       you automatically, then you may need to set  $LC_MESSAGES,  $LANG,\n"
               "       or  another system-dependent environment variable to indicate your\n"
               "       preferred locale, usually specified in the POSIX format:\n"
               "\n"
               "       <language>[_<territory>[.<character-set>[,<version>]]]\n"
               "\n"
               "       If the desired page is available in your locale, it will  be  dis‐\n"
               "       played in lieu of the standard (usually American English) page.\n"
               "\n"
               "       If  you  find that the translations supplied with this package are\n"
               "       not available in your native language and you would like to supply\n"
               "       them,  please contact the maintainer who will be coordinating such\n"
               "       activity.\n"
               "\n"
               "       Individual manual pages are normally written and maintained by the\n"
               "       maintainers  of  the  program,  function, or other topic that they\n"
               "       document, and are not included with this  package.   If  you  find\n"
               "       that a manual page is missing or inadequate, please report that to\n"
               "       the maintainers of the package in question.\n"
               "\n"
               "       For information regarding other features and extensions  available\n"
               "       with  this  manual  pager, please read the documents supplied with\n"
               "       the package.\n"
               "\n"
               "DEFAULTS\n"
               "       The order of sections to search may be overridden by the  environ‐\n"
               "       ment   variable   $MANSECT   or   by   the  SECTION  directive  in\n"
               "       /etc/man_db.conf.  By default it is as follows:\n"
               "\n"
               "              1 1p 8 2 3 3p 3pm 4 5 6 7 9 0p n l p o 1x 2x 3x 4x 5x 6x 7x\n"
               "              8x\n"
               "\n"
               "       The formatted manual page is displayed using a pager.  This can be\n"
               "       specified in a number of ways, or else will fall back to a default\n"
               "       (see option -P for details).\n"
               "\n"
               "       The  filters  are  deciphered  by a number of means.  Firstly, the\n"
               "       command line option -p or the environment variable $MANROFFSEQ  is\n"
               "       interrogated.  If -p was not used and the environment variable was\n"
               "       not set, the initial line of the nroff file is parsed for  a  pre‐\n"
               "       processor  string.   To  contain  a valid preprocessor string, the\n"
               "       first line must resemble\n"
               "\n"
               "       '\\\" <string>\n"
               "\n"
               "       where string can be any combination of letters described by option\n"
               "       -p below.\n"
               "\n"
               "       If  none  of  the  above methods provide any filter information, a\n"
               "       default set is used.\n"
               "\n"
               "       A formatting pipeline is formed from the filters and  the  primary\n"
               "       formatter  (nroff  or  [tg]roff  with  -t) and executed.  Alterna‐\n"
               "       tively, if an executable program mandb_nfmt  (or  mandb_tfmt  with\n"
               "       -t)  exists in the man tree root, it is executed instead.  It gets\n"
               "       passed the  manual  source  file,  the  preprocessor  string,  and\n"
               "       optionally the device specified with -T or -E as arguments.\n"
               "\n"
               "EXIT STATUS\n"
               "       0      Successful program execution.\n"
               "\n"
               "       1      Usage, syntax or configuration file error.\n"
               "\n"
               "       2      Operational error.\n"
               "\n"
               "       3      A child process returned a non-zero exit status.\n"
               "\n"
               "       16     At  least  one  of the pages/files/keywords didn't exist or\n"
               "              wasn't matched.\n"
               "\n"
               "FILES\n"
               "       /etc/man_db.conf\n"
               "              man-db configuration file.\n"
               "\n"
               "       /usr/share/man\n"
               "              A global manual page hierarchy.\n"
               "\n"
               "SEE ALSO\n"
               "       apropos(1), groff(1),  less(1),  manpath(1),  nroff(1),  troff(1),\n"
               "       whatis(1), zsoelim(1), manpath(5), man(7), catman(8), mandb(8)\n"
               "\n"
               "       Documentation for some packages may be available in other formats,\n"
               "       such as info(1) or HTML.\n"
               "\n"
               "HISTORY\n"
               "       1990,   1991   –   Originally   written   by   John    W.    Eaton\n"
               "       (jwe@che.utexas.edu).\n"
               "\n"
               "       Dec  23  1992: Rik Faith (faith@cs.unc.edu) applied bug fixes sup‐\n"
               "       plied by Willem Kasdorp (wkasdo@nikhefk.nikef.nl).\n"
               "\n"
               "       30th April 1994 – 23rd  February  2000:  Wilf.  (G.Wilford@ee.sur‐\n"
               "       rey.ac.uk)  has  been developing and maintaining this package with\n"
               "       the help of a few dedicated people.\n"
               "\n"
               "       30th October 1996  –  30th  March  2001:  Fabrizio  Polacco  <fpo‐\n"
               "       lacco@debian.org>  maintained  and  enhanced  this package for the\n"
               "       Debian project, with the help of all the community.\n"
               "\n"
               "       31st March 2001 – present day: Colin Watson  <cjwatson@debian.org>\n"
               "       is now developing and maintaining man-db.\n"
               "\n"
               "2.9.0                           2019-10-23                         MAN(1)\n");
    }else if(strcmp(argv[1], "help")==0)
        printf("NAME\n"
               "    help - Display information about builtin commands.\n"
               "\n"
               "SYNOPSIS\n"
               "    help [-dms] [pattern ...]\n"
               "\n"
               "DESCRIPTION\n"
               "    Display information about builtin commands.\n"
               "    \n"
               "    Displays brief summaries of builtin commands.  If PATTERN is\n"
               "    specified, gives detailed help on all commands matching PATTERN,\n"
               "    otherwise the list of help topics is printed.\n"
               "    \n"
               "    Options:\n"
               "      -d\toutput short description for each topic\n"
               "      -m\tdisplay usage in pseudo-manpage format\n"
               "      -s\toutput only a short usage synopsis for each topic matching\n"
               "    \t\tPATTERN\n"
               "    \n"
               "    Arguments:\n"
               "      PATTERN\tPattern specifying a help topic\n"
               "    \n"
               "    Exit Status:\n"
               "    Returns success unless PATTERN is not found or an invalid option is given.\n"
               "\n"
               "SEE ALSO\n"
               "    bash(1)\n"
               "\n"
               "IMPLEMENTATION\n"
               "    GNU bash, version 5.0.17(1)-release (x86_64-redhat-linux-gnu)\n"
               "    Copyright (C) 2019 Free Software Foundation, Inc.\n"
               "    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\n");
}
